#springboot的多环境配置
server:
  port: 8080
#  项目的访问路径
  servlet:
    context-path: /path
spring:
  profiles:
    active:
---
server:
  port: 8082
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod